---
title: "lab04-maiah-johnson"
output: html_document
---  
###Git Workshop
```{r, eval=FALSE}
git config --global user.name "johnson-ma"
git config --global user.email "maiahjohnson@berkeley.edu"
git config --global color.ui "auto"
git config --list
cd ~/Desktop
mkdir planets
git init
ls
ls -a
git status 
cd ~/Desktop
cd planets
ls -a
mkdir moons
cd moons
git init
ls -a   ##the moons subdirectory does not need to be a Git repository because the planets repository tracks all filles. subdirectories, under the planets  
rm -rf moons/.git ##removing the .git folder in the moons subdirectory 
cd ..
pwd 
nano mars.txt
Cold and dry, but everything is my favorite color  
ls
cat mars.txt
git status
git add mars.txt
git status
git commit -m "Start notes on Mars as a base"
git status 
git log 
nano mars.txt 
Cold and dry, but everything is my favorite color
The two moons may be a problem for Wolfman
cat mars.txt
git status
git diff
git add mars.txt
git commit -m "Add concerns about effects of Mars' moons on Wolfman"
nono mars.txt
cat mars.txt
git diff 
git add mars.txt
git diff
git siff --staged 
git commit -m "Discuss concerns abour Mars' climate for Mummy"
git status 
git log
git log -1
git log --oneline 
git log --oneline --graph --all --decorate 
mkdir directory
git status
git add directory
git status
git add <directory-with-files>  
  ##"Discuss effects of Mars' climate on Mummy" is the most appropriate for the last commit to be made to mars.txt
##git add myfile.txt
##$ git commit -m "my recent changes" would save the changes of myfile.txt to my local Git repository  
nano mars.txt
cat mars.txt
Maybe I should start with a base on Venus.
nano venus.txt
cat venus.txt
Venus is a nice planet and I defnitely should consider it as base.
git add mars.txt venus.txt
git commit -m "Write plans to start a base on Venus" ##adding text to mars.txt and creating new file venus.txt with additinal text 
cd .. 
mkdir bio 
cd bio
git init
nano me.txt
My name is maiah johnson 
I am from Atlanta, Georgia 
I have two dogs
nano me.txt
My name is maiah alyssa johnson 
I am from Atlanta, Georgia 
I have two dogs
I am a senior at UC Berkeley
cat me.txt
git add me.txt
git commit -m 'Adding biography file'
git diff me.txt
git log --format=full
mk dir results
touch a.dat b.dat c.dat results/a.out results/b.out
git status
nano .gitignore
$ touch a.dat b.dat c.dat results/a.out results/b.out
cat .gitignore
git status
git add .gitignore
git commit -m "Ignore data files and the results folder"
git status
git add a.dat
git status --ignored

if you only want to ignore the contents of results/plots, you can change your .gitignore to ignore only the /plots/ subfolder by adding the following line to your .gitignore: ##ignoring results/plots and not results/data  
to ignore all .data files in your root directory excet for final.data you would add the following lines(
*.data ##ignore all data files
!final.data ##except final.data  
Appending results/data/position/gps/*.data will match every file in results/data/position/gps that ends with .data. The file results/data/position/gps/info.txt will not be ignored. ##shortest .gitignore rule tou could write to ignore all .data files in result/data/position/gps  
given *.data !*.data all .data files will be tracked  

cd Desktop 
cd planets
git remote add origin https://github.com/johnson-ma/planets-.git
git remote -v
git push origin master
git pull origin master 

##GitHub GUI
1. left-most button (with the picture of a clipboard) copies the full 2. identifier of the commit to the clipboard
2. the middle button, you’ll see all of the changes that were made in that particular commit
3. right-most button lets you view all of the files in the repository at the time of that commit
##GitHub Timestamp 
GitHub displays timestamps in a human readable relative format  
##Push vs. commit  
When we push changes, we’re interacting with a remote repository to update it with the changes we’ve made locally; Commit only updates your local repository.  
##Fixing remote settings 
As soon as we try to use git push we’ll see an error message. The command git remote set-url allows us to change the remote’s URL to fix it.
```

###Creating a local Git Repository, Adding README file, Adding a remote, & Pushing changes to a remote repo
```{r, eval = FALSE}
cd Desktop
mkdir demo-repo
cd demo-repo
git init
echo "# Demo Repo" >> README.md
git add README.md
git status
git remote add origin https://github.com/johnson-ma/demo-repo.git
git remote -v
git status
git push origin master 

```

